name: flutter_local_device_discovery_example
description: "Example app for flutter_local_device_discovery."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_device_discovery:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
