name: flutter_local_device_discovery_platform_interface
description: >
  A common platform interface for the flutter_local_device_discovery plugin.
version: 1.1.0
homepage: https://github.com/amirsaleemahmad/flutter_local_device_discovery
repository: https://github.com/amirsaleemahmad/flutter_local_device_discovery.git
issue_tracker: https://github.com/amirsaleemahmad/flutter_local_device_discovery/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - device-discovery
  - local-network
  - networking
