name: flutter_local_device_discovery_darwin
description: >
  Apple platform implementation (iOS and macOS) of the
  flutter_local_device_discovery plugin.
version: 0.1.0
homepage: https://github.com/amirsaleemahmad/flutter_local_device_discovery
repository: https://github.com/amirsaleemahmad/flutter_local_device_discovery.git

environment:
  sdk: ^3.12.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_device_discovery_platform_interface: any
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterLocalDeviceDiscoveryPlugin
        sharedDarwinSource: true
        swiftPackage: true
      macos:
        pluginClass: FlutterLocalDeviceDiscoveryPlugin
        sharedDarwinSource: true
        swiftPackage: true
