name: flutter_local_device_discovery_android
description: >
  Android implementation of the flutter_local_device_discovery plugin.
version: 1.0.0
homepage: https://github.com/amirsaleemahmad/flutter_local_device_discovery
repository: https://github.com/amirsaleemahmad/flutter_local_device_discovery.git
issue_tracker: https://github.com/amirsaleemahmad/flutter_local_device_discovery/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_device_discovery_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterlocaldevicediscovery
        pluginClass: FlutterLocalDeviceDiscoveryPlugin
        dartPluginClass: FlutterLocalDeviceDiscoveryAndroid

topics:
  - device-discovery
  - mdns
  - dns-sd
  - android
  - networking
